# Generated by Django 6.0.4 on 2026-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment_account_number_payment_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], default='months', max_length=10),
        ),
    ]
