# Generated by Django 6.0.4 on 2026-05-05 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_membershipplan_duration_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_offered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='booked_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gymclass'),
        ),
    ]
