# Generated by Django 6.0.4 on 2026-05-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membershipplan_trainer_payment_booked_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='trainer',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='has_trainer_access',
            field=models.BooleanField(default=False, help_text='If true, member can select any trainer and class'),
        ),
    ]
