# Generated by Django 6.0.5 on 2026-05-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_membershipplan_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='classes/'),
        ),
    ]
