# Generated by Django 6.0.4 on 2026-05-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gymclass_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='duration_minutes',
            field=models.IntegerField(default=60, help_text='Duration of the class in minutes'),
        ),
    ]
