# Generated by Django 6.0.5 on 2026-06-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gymclass_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.CharField(blank=True, default='', help_text='Trainer specialty, e.g. Cardio Trainer, Bodybuilding Trainer', max_length=100),
        ),
    ]
